# -*- coding: utf-8 -*-
"""pdf_pipeline_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmDcSvzge5GLov-7CfglO_eWN9P04Otx

# 📄 PDF Pipeline Test Notebook

Test toàn bộ pipeline:

```
PDF/HTML
  └─▶ Layout Parser (pdfplumber / Docling)
       └─▶ DocumentIndex (sections, figures, tables, equations, bibliography)
            └─▶ [on highlight]
                 ├─ Step 1: Window Expansion
                 ├─ Step 2: Semantic Boundary Detection
                 └─ Step 3: Cross-Reference Resolution
```

---
**Setup**: Chạy các cell theo thứ tự từ trên xuống.

## 0️⃣ Install Dependencies
"""

# Core deps
!pip install -q pdfplumber spacy httpx nest_asyncio
!python -m spacy download en_core_web_sm -q

# Optional: Docling (nặng hơn, tốt hơn cho complex layout)
# !pip install -q docling

print('✅ Dependencies installed')

import nest_asyncio
nest_asyncio.apply()  # Fix: Jupyter/Colab already runs an event loop

import re
import json
import httpx
import asyncio
import dataclasses
from dataclasses import dataclass, field
from typing import Optional
from pathlib import Path
from pprint import pprint

import pdfplumber
import spacy

nlp = spacy.load('en_core_web_sm')
print('✅ All imports OK')

"""---
## 1️⃣ Layout Parser & DocumentIndex

Parse PDF → chunks có reading order đúng → build index.
"""

@dataclass
class Chunk:
    """Một đơn vị text sau khi parse."""
    idx:      int
    text:     str
    page:     int
    bbox:     Optional[tuple] = None   # (x0, y0, x1, y1)
    chunk_type: str = 'body'           # body | heading | caption | list | code | equation

    def __repr__(self):
        preview = self.text[:60].replace('\n', ' ')
        return f'Chunk(idx={self.idx}, page={self.page}, type={self.chunk_type}, text="{preview}...")'


@dataclass
class DocumentIndex:
    """Index được build một lần khi mở document."""
    chunks:      list[Chunk]          = field(default_factory=list)
    sections:    dict[str, int]       = field(default_factory=dict)  # '3.1' → chunk_idx
    figures:     dict[str, Chunk]     = field(default_factory=dict)  # '2'   → caption chunk
    tables:      dict[str, Chunk]     = field(default_factory=dict)  # '1'   → table chunk
    equations:   dict[str, Chunk]     = field(default_factory=dict)  # '4'   → equation chunk
    bibliography: dict[str, dict]     = field(default_factory=dict)  # '14'  → {title, authors, year}

    def resolve(self, ref_type: str, ref_id: str) -> Optional[str]:
        """O(1) lookup."""
        store = getattr(self, ref_type + 's', {})
        result = store.get(ref_id)
        if result is None:
            return None
        if isinstance(result, Chunk):
            return result.text
        if isinstance(result, dict):
            return json.dumps(result)
        return str(result)

    def stats(self):
        print(f'📦 DocumentIndex stats:')
        print(f'   Chunks      : {len(self.chunks)}')
        print(f'   Sections    : {len(self.sections)}')
        print(f'   Figures     : {len(self.figures)}')
        print(f'   Tables      : {len(self.tables)}')
        print(f'   Equations   : {len(self.equations)}')
        print(f'   Bibliography: {len(self.bibliography)}')

# ── Heading / figure / table / equation / bib detection ──────────────────────

SECTION_PATTERN  = re.compile(r'^(\d+(?:\.\d+)*)\s+(.+)', re.MULTILINE)
FIGURE_PATTERN   = re.compile(r'^[Ff]ig(?:ure)?[\s\.]*?(\d+[a-z]?)[\.:](.*)', re.MULTILINE)
TABLE_PATTERN    = re.compile(r'^[Tt]able\s+(\d+)[\.:](.*)',    re.MULTILINE)
EQUATION_PATTERN = re.compile(r'\\begin\{equation\}|\\\[|\$\$')  # LaTeX block start
BIB_PATTERN      = re.compile(
    r'\[(\d+)\]\s+([A-Z][^,]+),\s+(.+?\.),\s+(\d{4})',
    re.MULTILINE
)


def _classify_chunk(text: str) -> str:
    t = text.strip()
    if SECTION_PATTERN.match(t) and len(t.split('\n')[0]) < 100:
        return 'heading'
    if FIGURE_PATTERN.match(t):
        return 'caption'
    if TABLE_PATTERN.match(t):
        return 'caption'
    if EQUATION_PATTERN.search(t):
        return 'equation'
    if t.startswith('    ') or re.match(r'^(Algorithm|Procedure|function)', t):
        return 'code'

    # Detect algorithm/pseudocode: lines bắt đầu bằng số + dấu hai chấm
    algo_lines = [l for l in text.split('\n') if re.match(r'^\s*\d+:\s+', l)]
    if len(algo_lines) >= 2:
        return 'code'

    return 'body'


def parse_pdf_pdfplumber(pdf_path: str) -> DocumentIndex:
    """Parse PDF bằng pdfplumber, build DocumentIndex."""
    index = DocumentIndex()
    raw_blocks = []

    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages, start=1):
            # Extract words grouped by bbox blocks
            words = page.extract_words(use_text_flow=True, keep_blank_chars=False)
            if not words:
                continue

            # Group words into lines by y-coordinate tolerance
            lines, current_line, prev_y = [], [], None
            for w in words:
                if prev_y is None or abs(w['top'] - prev_y) < 5:
                    current_line.append(w['text'])
                else:
                    if current_line:
                        lines.append(' '.join(current_line))
                    current_line = [w['text']]
                prev_y = w['top']
            if current_line:
                lines.append(' '.join(current_line))

            raw_blocks.append({'page': page_num, 'lines': lines})

    # Build chunks from blocks
    chunk_idx = 0
    eq_counter = 0

    for block in raw_blocks:
        page = block['page']
        # Split block into sub-chunks on blank lines
        current_para = []
        for line in block['lines'] + ['']:
            if line.strip() == '' and current_para:
                text = '\n'.join(current_para)
                ctype = _classify_chunk(text)
                chunk = Chunk(idx=chunk_idx, text=text, page=page, chunk_type=ctype)
                index.chunks.append(chunk)

                # ── index by type ──
                if ctype == 'heading':
                    m = SECTION_PATTERN.match(text.strip())
                    if m:
                        index.sections[m.group(1)] = chunk_idx

                elif ctype == 'caption':
                    fm = FIGURE_PATTERN.match(text.strip())
                    tm = TABLE_PATTERN.match(text.strip())
                    if fm:
                        index.figures[fm.group(1)] = chunk
                    elif tm:
                        index.tables[tm.group(1)] = chunk

                elif ctype == 'equation':
                    eq_counter += 1
                    index.equations[str(eq_counter)] = chunk

                # Bibliography (inline detection)
                for m in BIB_PATTERN.finditer(text):
                    index.bibliography[m.group(1)] = {
                        'authors': m.group(2).strip(),
                        'title':   m.group(3).strip(),
                        'year':    m.group(4),
                    }

                chunk_idx += 1
                current_para = []
            elif line.strip():
                current_para.append(line)

    return index


print('✅ Parser functions defined')

# ── TEST với sample text (không cần PDF thật) ────────────────────────────────

SAMPLE_TEXT = """
1 Introduction

Dense retrieval has become a standard approach for open-domain QA [1, 2].
In this paper, we propose a new method based on contrastive learning.
See Section 3.1 for details on the training objective.

2 Related Work

Prior work by Smith et al. [3] explored bi-encoder architectures.
The approach in [4] used cross-encoders but suffered from high latency.

3 Method

Our method consists of two components as shown in Figure 1.

3.1 Training Objective

We minimize the following loss (Equation 1):
$$L = -\\log \\frac{e^{s(q,d^+)}}{\\sum_{d \\in D} e^{s(q,d)}}$$

3.2 Inference

At inference time, we encode all documents using the procedure below.

    Algorithm 1: Document Encoding
    Input: corpus D, encoder E
    Output: embeddings {e_d}
    for d in D:
        e_d = E(d)
    return {e_d}

Figure 1. Overview of our architecture. Left: encoder, Right: retriever.

Table 1. Comparison with baselines on NQ dataset.

4 Experiments

We evaluate on Natural Questions [1] and TriviaQA [2].
Results in Table 1 show our method outperforms all baselines.

References

[1] Karpukhin, Vladimir, Dense Passage Retrieval for Open-Domain QA., 2020
[2] Joshi, Mandar, TriviaQA: A Reading Comprehension Dataset., 2017
[3] Smith, John, Bi-Encoder Architectures for Retrieval., 2021
[4] Wang, Lei, Cross-Encoder Reranking at Scale., 2022
"""


def parse_text_to_index(text: str) -> DocumentIndex:
    """Parse plain text thay vì PDF — để test mà không cần file."""
    index = DocumentIndex()
    eq_counter = 0

    paragraphs = [p.strip() for p in text.split('\n\n') if p.strip()]

    for chunk_idx, para in enumerate(paragraphs):
        ctype = _classify_chunk(para)
        chunk = Chunk(idx=chunk_idx, text=para, page=1, chunk_type=ctype)
        index.chunks.append(chunk)

        if ctype == 'heading':
            m = SECTION_PATTERN.match(para)
            if m:
                index.sections[m.group(1)] = chunk_idx
        elif ctype == 'caption':
            fm = FIGURE_PATTERN.match(para)
            tm = TABLE_PATTERN.match(para)
            if fm: index.figures[fm.group(1)] = chunk
            elif tm: index.tables[tm.group(1)] = chunk
        elif ctype == 'equation':
            eq_counter += 1
            index.equations[str(eq_counter)] = chunk

        for m in BIB_PATTERN.finditer(para):
            index.bibliography[m.group(1)] = {
                'authors': m.group(2).strip(),
                'title':   m.group(3).strip(),
                'year':    m.group(4),
            }

    return index


# Build index từ sample text
doc_index = parse_text_to_index(SAMPLE_TEXT)
doc_index.stats()

print('\n--- Sections ---')
pprint(doc_index.sections)
print('\n--- Figures ---')
pprint({k: v.text for k, v in doc_index.figures.items()})
print('\n--- Tables ---')
pprint({k: v.text for k, v in doc_index.tables.items()})
print('\n--- Equations ---')
pprint({k: v.text for k, v in doc_index.equations.items()})
print('\n--- Bibliography ---')
pprint(doc_index.bibliography)

"""---
## 2️⃣ Step 1 — Window Expansion

Sliding window trên chunk list.
"""

def expand_window(index: DocumentIndex, highlight_idx: int, window: int = 3) -> list[Chunk]:
    """Lấy chunks lân cận xung quanh highlight_idx."""
    chunks = index.chunks
    start  = max(0, highlight_idx - window)
    end    = min(len(chunks), highlight_idx + window + 1)
    return chunks[start:end]


# ── TEST ──────────────────────────────────────────────────────────────────────
print('=== Step 1: Window Expansion Test ===')
print(f'Total chunks: {len(doc_index.chunks)}\n')

# Giả sử user highlight chunk idx=5 (chunk về 3.1 Training Objective)
for test_idx in [0, 5, len(doc_index.chunks)-1]:
    print(f'--- highlight_idx={test_idx}, window=2 ---')
    expanded = expand_window(doc_index, test_idx, window=2)
    for c in expanded:
        marker = '>>> ' if c.idx == test_idx else '    '
        print(f'{marker}[{c.idx}] ({c.chunk_type}) {c.text[:70].replace(chr(10), " ")}...')
    print()

"""---
## 3️⃣ Step 2 — Semantic Boundary Detection

Rule-based: sentence / code block / equation / list.
"""

# ── Sentence Boundary ─────────────────────────────────────────────────────────

def expand_to_sentence_boundary(text: str, highlight_end_char: int) -> str:
    """
    Mở rộng highlight đến hết câu hiện tại.
    Dùng spaCy để xử lý đúng abbreviations (et al., i.e., ...).
    """
    doc = nlp(text)
    for sent in doc.sents:
        if sent.end_char >= highlight_end_char:
            return text[:sent.end_char]
    return text  # fallback: trả về toàn bộ


# ── Code Block Boundary ───────────────────────────────────────────────────────

CODE_MARKERS = [
    'algorithm', 'procedure', 'function', 'for ', 'while ',
    'if ', 'return', 'input:', 'output:', 'def ', 'class ',
    'then', 'end if', 'end for', 'end while',
]

def is_inside_code_block(lines: list[str], highlight_line_idx: int, threshold: int = 2) -> bool:
    window = lines[max(0, highlight_line_idx-5): highlight_line_idx+5]
    score = sum(
        1 for line in window
        if any(m in line.lower() for m in CODE_MARKERS)
        or (line.startswith('    ') and line.strip())
    )
    return score >= threshold

def find_code_block_end(lines: list[str], start_idx: int) -> int:
    """Tìm dòng cuối của code block (blank line hoặc non-indented line)."""
    for i in range(start_idx, len(lines)):
        if i == start_idx:
            continue
        if not lines[i].strip() or (not lines[i].startswith('    ') and not lines[i].startswith('\t')):
            return i
    return len(lines)


# ── Equation Boundary ─────────────────────────────────────────────────────────

def is_partial_equation(text: str) -> bool:
    """True nếu text chứa LaTeX equation chưa đóng."""
    inline_unmatched = text.count('$') % 2 != 0
    block_unmatched  = text.count(r'\begin{equation}') != text.count(r'\end{equation}')
    bracket_unmatched = text.count(r'\[') != text.count(r'\]')
    dblock_unmatched  = text.count('$$') % 2 != 0
    return inline_unmatched or block_unmatched or bracket_unmatched or dblock_unmatched


# ── List Boundary ─────────────────────────────────────────────────────────────

LIST_PATTERN = re.compile(r'^(\s*[\•\-\*]|\s*\d+[\.\)])\s+')

def find_list_end(lines: list[str], start_idx: int) -> int:
    """Tìm dòng cuối của list."""
    for i in range(start_idx, len(lines)):
        if not lines[i].strip() or not LIST_PATTERN.match(lines[i]):
            return i
    return len(lines)


# ── Unified Semantic Boundary ──────────────────────────────────────────────────
def _find_algo_end(lines: list[str]) -> int:
    """
    Tìm dòng cuối của algorithm block.
    Algorithm kết thúc khi gặp dòng không phải: số+colon, keyword, math, hoặc blank.
    """
    ALGO_LINE = re.compile(
        r'^\s*(\d+:\s+'           # numbered line: "7: δ ← ..."
        r'|end\s+(if|for|while)'  # closing keywords
        r'|then$'                 # then
        r'|break$'                # break
        r'|[∑∈𝒙𝜹𝑝𝑿𝕀←≠]'        # unicode math symbols
        r'|[!<>]$'                # stray math chars from PDF parse
        r'|\s*$'                  # blank line
        r')'
    )
    last_algo_line = 0
    for i, line in enumerate(lines):
        if ALGO_LINE.match(line):
            last_algo_line = i
        elif i > 0 and last_algo_line > 0:
            # Gặp dòng body text sau khi đã có algo lines → dừng
            break
    return last_algo_line + 1

def apply_semantic_boundary(chunk: Chunk, highlight_end_char: int) -> str:
    """
    Áp dụng semantic boundary phù hợp dựa trên loại chunk.
    Trả về text đã được mở rộng đến boundary.
    """
    text  = chunk.text
    lines = text.split('\n')

    algo_lines = [l for l in lines if re.match(r'^\s*\d+:\s+', l)]
    is_code = chunk.chunk_type == 'code' or len(algo_lines) >= 2

    if chunk.chunk_type == 'equation' or is_partial_equation(text[:highlight_end_char]):
        boundary_type = 'equation'
        result = text  # equation luôn lấy toàn bộ

    elif is_code:
        boundary_type = 'code'
        # Chỉ lấy đến hết algorithm, bỏ phần body text phía sau
        end_line = _find_algo_end(lines)
        result = '\n'.join(lines[:end_line])

    elif LIST_PATTERN.match(text.split('\n')[0] if text.strip() else ''):
        boundary_type = 'list'
        end_line = find_list_end(lines, 0)
        result = '\n'.join(lines[:end_line])

    else:
        boundary_type = 'sentence'
        result = expand_to_sentence_boundary(text, highlight_end_char)

    return result, boundary_type


print('✅ Semantic boundary functions defined')

# ── TEST Step 2 ───────────────────────────────────────────────────────────────
print('=== Step 2: Semantic Boundary Detection Test ===\n')

test_cases = [
    {
        'name': 'Sentence boundary (mid-sentence highlight)',
        'text': 'Dense retrieval has become a standard approach for open-domain QA [1, 2]. In this paper, we propose a new method based on contrastive learning. See Section 3.1 for details on the training objective.',
        'highlight_end': 72,   # kết thúc giữa câu thứ 2
        'chunk_type': 'body',
    },
    {
        'name': 'Equation boundary (partial LaTeX)',
        'text': r'$$L = -\log \frac{e^{s(q,d^+)}}{\sum_{d \in D} e^{s(q,d)}}$$',
        'highlight_end': 10,
        'chunk_type': 'equation',
    },
    {
        'name': 'Code block boundary',
        'text': '    Algorithm 1\n    Input: corpus D\n    for d in D:\n        e_d = E(d)\n    return {e_d}',
        'highlight_end': 20,
        'chunk_type': 'code',
    },
    {
        'name': 'List boundary',
        'text': '- Item one\n- Item two\n- Item three\n\nSome body text after.',
        'highlight_end': 12,
        'chunk_type': 'body',
    },
]

for tc in test_cases:
    chunk = Chunk(idx=0, text=tc['text'], page=1, chunk_type=tc['chunk_type'])
    result, btype = apply_semantic_boundary(chunk, tc['highlight_end'])
    print(f"📌 {tc['name']}")
    print(f"   Boundary type : {btype}")
    print(f"   Original end  : char {tc['highlight_end']} → '{tc['text'][tc['highlight_end']-5:tc['highlight_end']+5]}'")
    print(f"   Expanded text : {result[:120].replace(chr(10),' ')}...")
    print()

"""---
## 4️⃣ Step 3 — Cross-Reference Resolution

Detect refs trong text → resolve từ DocumentIndex → fetch Semantic Scholar nếu cần.
"""

# ── Pattern Detection ─────────────────────────────────────────────────────────

CROSS_REF_PATTERNS = {
    'section':  re.compile(r'[Ss]ections?\s+(\d+(?:\.\d+)*)', re.IGNORECASE),
    'figure':   re.compile(r'[Ff]ig(?:ure)?\.?\s*(\d+[a-z]?)',  re.IGNORECASE),
    'table':    re.compile(r'[Tt]able\s+(\d+)',                  re.IGNORECASE),
    'equation': re.compile(r'[Ee]q(?:uation)?\.?\s*\(?(\d+)\)?', re.IGNORECASE),
    'citation': re.compile(r'\[(\d+(?:,\s*\d+)*)\]'),
    'appendix': re.compile(r'[Aa]ppendix\s+([A-Z])',             re.IGNORECASE),
}


def detect_references(text: str) -> dict[str, list[str]]:
    """Tìm tất cả cross-references trong text."""
    found = {}
    for ref_type, pattern in CROSS_REF_PATTERNS.items():
        matches = pattern.findall(text)
        if matches:
            # Citation có thể là '1, 2, 3' → split ra
            if ref_type == 'citation':
                ids = []
                for m in matches:
                    ids.extend(x.strip() for x in m.split(','))
                found[ref_type] = list(dict.fromkeys(ids))  # dedupe, preserve order
            else:
                found[ref_type] = list(dict.fromkeys(matches))
    return found


# ── Semantic Scholar API ───────────────────────────────────────────────────────

async def fetch_abstract_from_s2(title: str) -> Optional[str]:
    """Fetch abstract từ Semantic Scholar API (free, no auth)."""
    try:
        url = 'https://api.semanticscholar.org/graph/v1/paper/search'
        params = {'query': title, 'fields': 'abstract,year,authors', 'limit': 1}
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.get(url, params=params)
            data = resp.json()
        papers = data.get('data', [])
        if papers:
            return papers[0].get('abstract')
    except Exception as e:
        print(f'   ⚠️  S2 API error: {e}')
    return None


# ── Resolution Pipeline ────────────────────────────────────────────────────────

async def resolve_references(
    text: str,
    index: DocumentIndex,
    fetch_abstracts: bool = True
) -> list[tuple[str, str, str]]:
    """
    Detect + resolve tất cả references trong text.
    Returns: list of (ref_type, ref_id, resolved_content)
    """
    refs    = detect_references(text)
    results = []

    for ref_type, ids in refs.items():
        for ref_id in ids:

            if ref_type == 'citation':
                bib = index.bibliography.get(ref_id)
                if bib:
                    content = f"{bib['authors']} ({bib['year']}): {bib['title']}"
                    if fetch_abstracts:
                        abstract = await fetch_abstract_from_s2(bib['title'])
                        if abstract:
                            content += f' | Abstract: {abstract[:200]}...'
                    results.append((ref_type, ref_id, content))
                else:
                    results.append((ref_type, ref_id, '[bibliography entry not found]'))

            else:
                # section / figure / table / equation
                resolved = index.resolve(ref_type, ref_id)
                if resolved:
                    results.append((ref_type, ref_id, resolved[:300]))
                else:
                    results.append((ref_type, ref_id, f'[{ref_type} {ref_id} not found in document]'))

    return results


print('✅ Cross-reference functions defined')

# ── TEST Step 3: Pattern Detection ────────────────────────────────────────────
print('=== Step 3a: Reference Detection Test ===\n')

test_texts = [
    'Results in Table 1 show improvement. See Figure 2a and Section 3.1.',
    'We follow the approach of [1, 2, 3] and extend it as described in Eq. (4).',
    'The loss in Equation 1 is derived from [14]. See Appendix A for proof.',
]

for t in test_texts:
    refs = detect_references(t)
    print(f'Text: "{t}"')
    print(f'Refs: {refs}\n')

# ── TEST Step 3: Full Resolution (với DocumentIndex) ──────────────────────────
print('=== Step 3b: Full Resolution Test (no Semantic Scholar) ===\n')

highlight_text = (
    'We minimize the following loss (Equation 1). '
    'Results in Table 1 show our method outperforms all baselines. '
    'See Section 3.1 for training details. Prior work [1, 2] used different approaches.'
)

# Sync test (no abstract fetch)
async def test_resolution():
    results = await resolve_references(highlight_text, doc_index, fetch_abstracts=False)
    return results

resolved = await test_resolution()

print(f'Detected & resolved {len(resolved)} references:\n')
for ref_type, ref_id, content in resolved:
    print(f'  [{ref_type} {ref_id}]')
    print(f'   → {content[:150].replace(chr(10), " ")}\n')

# ── TEST Step 3: Semantic Scholar API (live) ──────────────────────────────────
# Chỉ chạy cell này nếu có internet và muốn test API thật
print('=== Step 3c: Semantic Scholar API Test ===\n')

async def test_s2_api():
    title = 'Dense Passage Retrieval for Open-Domain Question Answering'
    print(f'Fetching abstract for: "{title}"')
    abstract = await fetch_abstract_from_s2(title)
    if abstract:
        print(f'✅ Abstract (first 300 chars):\n{abstract[:300]}...')
    else:
        print('❌ No abstract found (check internet connection)')

await test_s2_api()

"""---
## 5️⃣ Full Pipeline End-to-End

Ghép tất cả lại: text → DocumentIndex → highlight → Step 1 → Step 2 → Step 3 → Enriched Prompt.
"""

@dataclass
class HighlightContext:
    highlight_text:    str
    expanded_chunks:   list[Chunk]
    boundary_text:     str
    boundary_type:     str
    resolved_refs:     list[tuple[str, str, str]]


async def process_highlight(
    index:           DocumentIndex,
    highlight_text:  str,
    highlight_chunk_idx: int,
    highlight_end_char:  int,
    window:          int  = 1,
    fetch_abstracts: bool = False,
) -> HighlightContext:
    """
    Full pipeline: window expansion → semantic boundary → cross-ref resolution.
    """
    # Step 1: Window Expansion
    expanded = expand_window(index, highlight_chunk_idx, window=window)

    # Step 2: Semantic Boundary
    highlight_chunk = index.chunks[highlight_chunk_idx]
    boundary_text, boundary_type = apply_semantic_boundary(
        highlight_chunk, highlight_end_char
    )

    # Step 3: Cross-Ref Resolution
    # Detect refs trong highlight + expanded context
    full_context = highlight_text + ' ' + ' '.join(c.text for c in expanded)
    resolved = await resolve_references(full_context, index, fetch_abstracts=fetch_abstracts)

    return HighlightContext(
        highlight_text  = highlight_text,
        expanded_chunks = expanded,
        boundary_text   = boundary_text,
        boundary_type   = boundary_type,
        resolved_refs   = resolved,
    )


def build_prompt(ctx: HighlightContext, mode: str = 'ask') -> str:
    """Build enriched prompt từ HighlightContext."""
    expanded_text = '\n---\n'.join(c.text for c in ctx.expanded_chunks)

    prompt = f"""You are analyzing an academic paper.

HIGHLIGHTED TEXT (what the user selected):
{ctx.highlight_text}

BOUNDARY TYPE DETECTED: {ctx.boundary_type}
EXPANDED TO BOUNDARY:
{ctx.boundary_text}

SURROUNDING CONTEXT (±window chunks):
{expanded_text}
"""

    if ctx.resolved_refs:
        prompt += '\nRESOLVED REFERENCES:\n'
        for ref_type, ref_id, content in ctx.resolved_refs:
            prompt += f'  [{ref_type} {ref_id}]: {content[:200]}\n'

    if mode == 'ask':
        prompt += """
Answer specifically about the highlighted text.
Use surrounding context and resolved references to inform your answer.
"""
    elif mode == 'save':
        prompt += """
Extract a complete, self-contained knowledge unit from the highlighted text.
Return JSON with: completed_text, suggested_type (concept|method|result|insight), summary.
Return ONLY JSON, no preamble.
"""

    return prompt


print('✅ End-to-end pipeline defined')

# ── FULL PIPELINE TEST ────────────────────────────────────────────────────────
print('=== Full Pipeline Test ===\n')

# Tìm chunk chứa training objective
target_text = 'We minimize the following loss'
target_idx  = next(
    (c.idx for c in doc_index.chunks if target_text in c.text), 5
)

print(f'Simulating highlight on chunk {target_idx}:')
print(f'  "{doc_index.chunks[target_idx].text[:80]}..."\n')

async def run_full_pipeline():
    ctx = await process_highlight(
        index               = doc_index,
        highlight_text      = doc_index.chunks[target_idx].text,
        highlight_chunk_idx = target_idx,
        highlight_end_char  = 35,   # user highlights đến char 35
        window              = 1,
        fetch_abstracts     = False,
    )
    return ctx

ctx = await run_full_pipeline()

print(f'📍 Step 1 — Expanded chunks: {[c.idx for c in ctx.expanded_chunks]}')
print(f'📍 Step 2 — Boundary type: {ctx.boundary_type}')
print(f'📍 Step 2 — Boundary text: {ctx.boundary_text[:100]}...')
print(f'📍 Step 3 — Resolved refs: {len(ctx.resolved_refs)}')
for rt, rid, rc in ctx.resolved_refs:
    print(f'     [{rt} {rid}]: {rc[:100]}')

print('\n' + '='*60)
print('GENERATED PROMPT (mode=ask):')
print('='*60)
print(build_prompt(ctx, mode='ask'))

"""---
## 6️⃣ Test với PDF thật (optional)

Upload PDF lên Colab rồi chạy cell này.
"""

# ── Upload PDF ────────────────────────────────────────────────────────────────
from google.colab import files

uploaded = files.upload()  # Upload file PDF của bạn
pdf_path = list(uploaded.keys())[0]
print(f'Uploaded: {pdf_path}')

# ── Parse PDF thật ────────────────────────────────────────────────────────────
real_index = parse_pdf_pdfplumber(pdf_path)
real_index.stats()

print('\nFirst 5 chunks:')
for c in real_index.chunks[:5]:
    print(f'  [{c.idx}] ({c.chunk_type}) page={c.page} | {c.text[:80].replace(chr(10)," ")}...')

# ── Simulate highlight trên PDF thật ─────────────────────────────────────────
# Thay đổi chunk_idx và end_char theo nội dung PDF của bạn
HIGHLIGHT_CHUNK_IDX = 4   # ← thay số này
HIGHLIGHT_END_CHAR  = 10   # ← thay số này

if HIGHLIGHT_CHUNK_IDX < len(real_index.chunks):
    target_chunk = real_index.chunks[HIGHLIGHT_CHUNK_IDX]
    print(f'Highlighting chunk {HIGHLIGHT_CHUNK_IDX}:')
    print(f'  Full text: "{target_chunk.text[:200]}"\n')

    async def run_real_pdf():
        return await process_highlight(
            index               = real_index,
            highlight_text      = target_chunk.text[:HIGHLIGHT_END_CHAR],
            highlight_chunk_idx = HIGHLIGHT_CHUNK_IDX,
            highlight_end_char  = HIGHLIGHT_END_CHAR,
            window              = 1,
            fetch_abstracts     = True,   # ← set False nếu offline
        )

    real_ctx = await run_real_pdf()

    print(f'Step 1 — Expanded: {[c.idx for c in real_ctx.expanded_chunks]}')
    print(f'Step 2 — Boundary: {real_ctx.boundary_type}')
    print(f'Step 3 — Refs: {[(r[0], r[1]) for r in real_ctx.resolved_refs]}')
    print('\n--- Prompt ---')
    print(build_prompt(real_ctx, mode='ask'))
else:
    print(f'⚠️  Chunk idx {HIGHLIGHT_CHUNK_IDX} out of range (total: {len(real_index.chunks)})')

"""---
## 7️⃣ Docling Integration (optional, tốt hơn cho complex layout)

Docling cho reading order chính xác hơn trên multi-column papers.
"""

# Chỉ chạy nếu đã cài: !pip install docling

def parse_pdf_docling(pdf_path: str) -> DocumentIndex:
    """Parse PDF bằng Docling — tốt hơn cho multi-column, figures, tables."""
    try:
        from docling.document_converter import DocumentConverter
    except ImportError:
        print('❌ Docling not installed. Run: !pip install docling')
        return DocumentIndex()

    converter = DocumentConverter()
    result    = converter.convert(pdf_path)
    doc       = result.document

    index      = DocumentIndex()
    eq_counter = 0

    for chunk_idx, element in enumerate(doc.texts):
        text   = element.text
        page   = element.prov[0].page_no if element.prov else 1
        ctype  = _classify_chunk(text)

        # Docling provides explicit element types
        etype = type(element).__name__.lower()
        if 'section' in etype or 'heading' in etype:
            ctype = 'heading'
        elif 'figure' in etype:
            ctype = 'caption'
        elif 'table' in etype:
            ctype = 'caption'
        elif 'equation' in etype or 'formula' in etype:
            ctype = 'equation'

        chunk = Chunk(idx=chunk_idx, text=text, page=page, chunk_type=ctype)
        index.chunks.append(chunk)

        if ctype == 'heading':
            m = SECTION_PATTERN.match(text)
            if m: index.sections[m.group(1)] = chunk_idx
        elif ctype == 'caption':
            fm = FIGURE_PATTERN.match(text)
            tm = TABLE_PATTERN.match(text)
            if fm: index.figures[fm.group(1)] = chunk
            elif tm: index.tables[tm.group(1)] = chunk
        elif ctype == 'equation':
            eq_counter += 1
            index.equations[str(eq_counter)] = chunk

        for m in BIB_PATTERN.finditer(text):
            index.bibliography[m.group(1)] = {
                'authors': m.group(2).strip(),
                'title':   m.group(3).strip(),
                'year':    m.group(4),
            }

    return index


print('✅ Docling parser defined (install docling to use)')

!pip install docling

parse_pdf_docling("/content/2108.04979v1.pdf")